import { FamilyMember, CategoryBudget, SavingsGoal, DebtItem, Transaction, AppSettings } from '../types';
import { getTodayDate } from './formatters';

export const INITIAL_MEMBERS: FamilyMember[] = [
  { id: 'mem-1', name: 'মো: রফিকুল ইসলাম (বাবা)', role: 'বাবা', avatarColor: '#10b981', phone: '01711000001', monthlyTarget: 60000 },
  { id: 'mem-2', name: 'নাসরিন সুলতানা (মা)', role: 'মা', avatarColor: '#ec4899', phone: '01811000002', monthlyTarget: 15000 },
  { id: 'mem-3', name: 'তানভীর আহমেদ (ভাই)', role: 'ভাই', avatarColor: '#3b82f6', phone: '01911000003', monthlyTarget: 35000 },
  { id: 'mem-4', name: 'সুমাইয়া আক্তার (বোন)', role: 'বোন', avatarColor: '#8b5cf6', phone: '01611000004' },
];

export const INITIAL_BUDGETS: CategoryBudget[] = [
  { category: '🛒 বাজার', amount: 15000 },
  { category: '🏠 বাসা', amount: 20000 },
  { category: '💡 বিদ্যুৎ', amount: 3500 },
  { category: '💧 পানি', amount: 1000 },
  { category: '🔥 গ্যাস', amount: 1500 },
  { category: '📱 মোবাইল/ইন্টারনেট', amount: 2500 },
  { category: '🏥 চিকিৎসা', amount: 5000 },
  { category: '🎓 শিক্ষা', amount: 8000 },
  { category: '🚗 যাতায়াত', amount: 4500 },
  { category: '🍽️ খাবার', amount: 6000 },
  { category: '👕 পোশাক', amount: 5000 },
  { category: '🛍️ কেনাকাটা', amount: 4000 },
  { category: '🧾 বিল', amount: 2000 },
];

export const INITIAL_SAVINGS: SavingsGoal[] = [
  {
    id: 'sav-1',
    title: 'জরুরী পারিবারিক ফান্ড',
    targetAmount: 100000,
    currentAmount: 65000,
    targetDate: '2026-12-31',
    note: 'যেকোনো আকস্মিক স্বাস্থ্য বা পারিবারিক প্রয়োজনের জন্য সংরক্ষিত',
    createdAt: Date.now() - 30 * 86400000,
  },
  {
    id: 'sav-2',
    title: 'ছোট ভাইয়ের নতুন ল্যাপটপ',
    targetAmount: 60000,
    currentAmount: 35000,
    targetDate: '2026-10-15',
    note: 'ফ্রিল্যান্সিং ও পড়াশোনার জন্য ভালো কনফিগারেশনের ল্যাপটপ',
    createdAt: Date.now() - 15 * 86400000,
  },
  {
    id: 'sav-3',
    title: 'বাৎসরিক পরিবার ভ্রমণ (কক্সবাজার)',
    targetAmount: 30000,
    currentAmount: 18000,
    targetDate: '2026-11-20',
    note: 'শীতের ছুটিতে পুরো পরিবারের ভ্রমণ খরচ',
    createdAt: Date.now() - 10 * 86400000,
  },
];

export const INITIAL_DEBTS: DebtItem[] = [
  {
    id: 'debt-1',
    type: 'receivable',
    personName: 'কামাল হোসেন (বন্ধু)',
    phone: '01723456789',
    amount: 15000,
    paidAmount: 5000,
    date: '2026-08-01',
    dueDate: '2026-09-15',
    note: 'জরুরী ব্যবসায়িক প্রয়োজনে ধার নিয়েছিলেন',
    status: 'partial',
    payments: [
      { id: 'pay-1', date: '2026-08-15', amount: 5000, note: 'বিকাশের মাধ্যমে আংশিক পরিশোধ' }
    ],
    createdAt: Date.now() - 20 * 86400000,
  },
  {
    id: 'debt-2',
    type: 'payable',
    personName: 'মামুন মামা',
    phone: '01898765432',
    amount: 8000,
    paidAmount: 0,
    date: '2026-08-10',
    dueDate: '2026-09-05',
    note: 'বাসার সংস্কার কাজের জন্য ধার নেওয়া হয়েছিল',
    status: 'pending',
    payments: [],
    createdAt: Date.now() - 12 * 86400000,
  }
];

export const INITIAL_SETTINGS: AppSettings = {
  appName: 'টুকটুকির সংসার',
  currencySymbol: '৳',
  currencyCode: 'BDT',
  language: 'bn',
  theme: 'light',
  numberFormat: 'english',
};

// Generate sample transactions spread over current month and recent days
export function getInitialTransactions(): Transaction[] {
  const today = new Date();
  const year = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, '0');
  const d = (day: number) => `${year}-${month}-${String(day).padStart(2, '0')}`;

  return [
    {
      id: 'TXN-1001',
      date: d(1),
      time: '10:30',
      type: 'income',
      memberId: 'mem-1',
      memberName: 'মো: রফিকুল ইসলাম (বাবা)',
      category: 'বেতন',
      amount: 55000,
      paymentMethod: 'bank',
      note: 'আগস্ট মাসের সরকারি বেতন',
      createdAt: Date.now() - 25 * 86400000,
    },
    {
      id: 'TXN-1002',
      date: d(2),
      time: '14:15',
      type: 'income',
      memberId: 'mem-3',
      memberName: 'তানভীর আহমেদ (ভাই)',
      category: 'Freelance',
      amount: 32000,
      paymentMethod: 'bank',
      note: 'Upwork প্রোজেক্ট পেমেন্ট',
      createdAt: Date.now() - 24 * 86400000,
    },
    {
      id: 'TXN-1003',
      date: d(2),
      time: '16:00',
      type: 'expense',
      memberId: 'mem-1',
      memberName: 'মো: রফিকুল ইসলাম (বাবা)',
      category: '🏠 বাসা',
      subcategory: 'বাসা ভাড়া',
      amount: 20000,
      paymentMethod: 'bank',
      note: 'আগস্ট মাসের ফ্ল্যাট ভাড়া',
      createdAt: Date.now() - 24 * 86400000,
    },
    {
      id: 'TXN-1004',
      date: d(3),
      time: '09:45',
      type: 'expense',
      memberId: 'mem-2',
      memberName: 'নাসরিন সুলতানা (মা)',
      category: '🛒 বাজার',
      subcategory: 'চাল-ডাল ও মশলা',
      amount: 4800,
      paymentMethod: 'cash',
      note: 'মাসের চাল, ডাল, তেল ও মশলা কেনা',
      createdAt: Date.now() - 23 * 86400000,
    },
    {
      id: 'TXN-1005',
      date: d(5),
      time: '11:20',
      type: 'expense',
      memberId: 'mem-1',
      memberName: 'মো: রফিকুল ইসলাম (বাবা)',
      category: '💡 বিদ্যুৎ',
      subcategory: 'বিদ্যুৎ বিল (প্রিপেইড/পোস্টপেইড)',
      amount: 3150,
      paymentMethod: 'mobile_banking',
      note: 'ডেসকো প্রিপেইড মিটার রিচার্জ',
      createdAt: Date.now() - 21 * 86400000,
    },
    {
      id: 'TXN-1006',
      date: d(7),
      time: '18:30',
      type: 'expense',
      memberId: 'mem-3',
      memberName: 'তানভীর আহমেদ (ভাই)',
      category: '📱 মোবাইল/ইন্টারনেট',
      subcategory: 'ব্রডব্যান্ড ইন্টারনেট বিল',
      amount: 1500,
      paymentMethod: 'mobile_banking',
      note: 'মাসিক ব্রডব্যান্ড বিল',
      createdAt: Date.now() - 19 * 86400000,
    },
    {
      id: 'TXN-1007',
      date: d(10),
      time: '10:00',
      type: 'expense',
      memberId: 'mem-2',
      memberName: 'নাসরিন সুলতানা (মা)',
      category: '🛒 বাজার',
      subcategory: 'মাছ-মাংস',
      amount: 3600,
      paymentMethod: 'cash',
      note: 'রুই মাছ, মুরগী ও ডিম কেনা',
      createdAt: Date.now() - 16 * 86400000,
    },
    {
      id: 'TXN-1008',
      date: d(12),
      time: '15:10',
      type: 'income',
      memberId: 'mem-2',
      memberName: 'নাসরিন সুলতানা (মা)',
      category: 'ব্যবসা',
      amount: 8500,
      paymentMethod: 'mobile_banking',
      note: 'বুটিক পোশাক বিক্রয় লভ্যাংশ',
      createdAt: Date.now() - 14 * 86400000,
    },
    {
      id: 'TXN-1009',
      date: d(14),
      time: '19:40',
      type: 'expense',
      memberId: 'mem-1',
      memberName: 'মো: রফিকুল ইসলাম (বাবা)',
      category: '🏥 চিকিৎসা',
      subcategory: 'ওষুধ',
      amount: 2450,
      paymentMethod: 'cash',
      note: 'ডায়াবেটিস ও প্রেশারের এক মাসের ওষুধ',
      createdAt: Date.now() - 12 * 86400000,
    },
    {
      id: 'TXN-1010',
      date: d(18),
      time: '12:00',
      type: 'expense',
      memberId: 'mem-4',
      memberName: 'সুমাইয়া আক্তার (বোন)',
      category: '🎓 শিক্ষা',
      subcategory: 'স্কুল/কলেজ ফি',
      amount: 4500,
      paymentMethod: 'mobile_banking',
      note: 'কলেজের সেমিস্টার ফি ও বই কেনা',
      createdAt: Date.now() - 8 * 86400000,
    },
    {
      id: 'TXN-1011',
      date: d(22),
      time: '20:15',
      type: 'expense',
      memberId: 'mem-3',
      memberName: 'তানভীর আহমেদ (ভাই)',
      category: '🍽️ খাবার',
      subcategory: 'রেস্তোরাঁ',
      amount: 1850,
      paymentMethod: 'mobile_banking',
      note: 'পরিবার নিয়ে রাতের ডিনার',
      createdAt: Date.now() - 4 * 86400000,
    },
    {
      id: 'TXN-1012',
      date: getTodayDate(),
      time: '09:15',
      type: 'expense',
      memberId: 'mem-1',
      memberName: 'মো: রফিকুল ইসলাম (বাবা)',
      category: '🛒 বাজার',
      subcategory: 'কাঁচাবাজার',
      amount: 1200,
      paymentMethod: 'cash',
      note: 'আজকের তাজা শাকসবজি ও ফলমূল',
      createdAt: Date.now() - 3600000,
    },
    {
      id: 'TXN-1013',
      date: getTodayDate(),
      time: '11:00',
      type: 'income',
      memberId: 'mem-3',
      memberName: 'তানভীর আহমেদ (ভাই)',
      category: 'Freelance',
      amount: 12000,
      paymentMethod: 'bank',
      note: 'লোকাল ক্লায়েন্ট ওয়েবসাইট ডিজাইন পেমেন্ট',
      createdAt: Date.now() - 1800000,
    }
  ];
}

export const INITIAL_SAMPLE_MEMBERS = INITIAL_MEMBERS;
export const INITIAL_SAMPLE_BUDGETS = INITIAL_BUDGETS;
export const INITIAL_SAMPLE_GOALS = INITIAL_SAVINGS;
export const INITIAL_SAMPLE_DEBTS = INITIAL_DEBTS;
export const INITIAL_SAMPLE_TRANSACTIONS = getInitialTransactions();
